package org.redhat.api.item;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class ItemModel implements Serializable {
	

	@Id
    @GeneratedValue
	private long id;
	
	private String year;
	
	private String make;
	
	private String model;
	
	
	
	
	
	/*
	 * below this line is generated by the ide
	 */
	
	private static final long serialVersionUID = -7384751271101505737L;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getYear() {
		return year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMake() {
		return make;
	}

	public void setMake(String make) {
		this.make = make;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String toString() {
		return "ItemModel [id=" + id + ", year=" + year + ", make=" + make + ", model=" + model + "]";
	}

}
